<template>
    <label class="form-label">Ícone</label>
    <div class="d-flex align-items-center">
        <input
            :data-error-class="`icone-${selectedIcon}`"
            type="text"
            :disabled="props.disabled"
            v-model="filterText"
            placeholder="Pesquisar ícones"
            class="form-control dropdown"
            @focus="dropdownOpen = true"
            @blur="closeDropdown"
        />
        <input type="hidden" v-model="selectedIcon" name="icone">
        <div v-if="selectedIcon" class="ms-2">
            <i :class="['fa', selectedIcon]" style="font-size: 24px;"></i>
        </div>
        <div v-else class="ms-2">
            <small class="ms-1">Sem ícone</small>
        </div>
    </div>
    <div class="dropdown" :class="{ show: dropdownOpen }">
        <div class="dropdown-menu" :class="{ show: dropdownOpen }">
            <div
                v-for="(icon, index) in filteredIcons"
                :key="index"
                :class="['p-1 fa-solid', icon.name, { 'selected': icon.name === selectedIcon }]"
                @click="selectIcon(icon.name)"
            ></div>
        </div>
    </div>
</template>
<script>
import {ref, computed, onMounted} from 'vue';

export default {
    setup(props, { emit }) {
        const icons = ref([
            { name: 'fa-wand-magic-sparkles', ptName: 'Livro de endereços' },
            { name: 'fa-adjust', ptName: 'Ajustar' },
            { name: 'fa-american-sign-language-interpreting', ptName: 'Interpretação de linguagem de sinais americana' },
            { name: 'fa-anchor', ptName: 'Âncora' },
            { name: 'fa-archive', ptName: 'Arquivo' },
            { name: 'fa-area-chart', ptName: 'Gráfico de área' },
            { name: 'fa-arrows', ptName: 'Setas' },
            { name: 'fa-arrows-h', ptName: 'Setas horizontais' },
            { name: 'fa-arrows-v', ptName: 'Setas verticais' },
            { name: 'fa-assistive-listening-systems', ptName: 'Sistemas de escuta assistiva' },
            { name: 'fa-asterisk', ptName: 'Asterisco' },
            { name: 'fa-at', ptName: 'Arroba' },
            { name: 'fa-audio-description', ptName: 'Descrição de áudio' },
            { name: 'fa-automobile', ptName: 'Automóvel' },
            { name: 'fa-ban', ptName: 'Proibição' },
            { name: 'fa-bank', ptName: 'Banco' },
            { name: 'fa-bar-chart', ptName: 'Gráfico de barras' },
            { name: 'fa-barcode', ptName: 'Código de barras' },
            { name: 'fa-bars', ptName: 'Barras' },
            { name: 'fa-bathtub', ptName: 'Banheira' },
            { name: 'fa-battery', ptName: 'Bateria' },
            { name: 'fa-battery-empty', ptName: 'Bateria vazia' },
            { name: 'fa-bed', ptName: 'Cama' },
            { name: 'fa-beer', ptName: 'Cerveja' },
            { name: 'fa-bell', ptName: 'Sino' },
            { name: 'fa-bell-slash', ptName: 'Sino com barra' },
            { name: 'fa-bicycle', ptName: 'Bicicleta' },
            { name: 'fa-binoculars', ptName: 'Binóculos' },
            { name: 'fa-birthday-cake', ptName: 'Bolo de aniversário' },
            { name: 'fa-blind', ptName: 'Cego' },
            { name: 'fa-bolt', ptName: 'Raio' },
            { name: 'fa-bomb', ptName: 'Bomba' },
            { name: 'fa-bookmark', ptName: 'Marcador' },
            { name: 'fa-braille', ptName: 'Braille' },
            { name: 'fa-briefcase', ptName: 'Pasta' },
            { name: 'fa-bug', ptName: 'Inseto' },
            { name: 'fa-building', ptName: 'Prédio' },
            { name: 'fa-bullhorn', ptName: 'Megafone' },
            { name: 'fa-bullseye', ptName: 'Alvo' },
            { name: 'fa-bus', ptName: 'Ônibus' },
            { name: 'fa-cab', ptName: 'Táxi' },
            { name: 'fa-calculator', ptName: 'Calculadora' },
            { name: 'fa-calendar', ptName: 'Calendário' },
            { name: 'fa-camera', ptName: 'Câmera' },
            { name: 'fa-camera-retro', ptName: 'Câmera retro' },
            { name: 'fa-car', ptName: 'Carro' },
            { name: 'fa-cart-arrow-down', ptName: 'Carrinho com seta para baixo' },
            { name: 'fa-cart-plus', ptName: 'Carrinho com mais' },
            { name: 'fa-certificate', ptName: 'Certificado' },
            { name: 'fa-check', ptName: 'Verificar' },
            { name: 'fa-check-circle', ptName: 'Círculo de verificação' },
            { name: 'fa-check-square', ptName: 'Quadrado de verificação' },
            { name: 'fa-child', ptName: 'Criança' },
            { name: 'fa-circle', ptName: 'Círculo' },
            { name: 'fa-clone', ptName: 'Clonar' },
            { name: 'fa-close', ptName: 'Fechar' },
            { name: 'fa-cloud', ptName: 'Nuvem' },
            { name: 'fa-cloud-download', ptName: 'Download de nuvem' },
            { name: 'fa-cloud-upload', ptName: 'Upload de nuvem' },
            { name: 'fa-code', ptName: 'Código' },
            { name: 'fa-code-fork', ptName: 'Ramificação de código' },
            { name: 'fa-coffee', ptName: 'Café' },
            { name: 'fa-cog', ptName: 'Engrenagem' },
            { name: 'fa-cogs', ptName: 'Engrenagens' },
            { name: 'fa-comment', ptName: 'Comentário' },
            { name: 'fa-commenting', ptName: 'Comentando' },
            { name: 'fa-comments', ptName: 'Comentários' },
            { name: 'fa-compass', ptName: 'Bússola' },
            { name: 'fa-copyright', ptName: 'Direitos autorais' },
            { name: 'fa-creative-commons', ptName: 'Creative Commons' },
            { name: 'fa-credit-card', ptName: 'Cartão de crédito' },
            { name: 'fa-crop', ptName: 'Cortar' },
            { name: 'fa-crosshairs', ptName: 'Mira' },
            { name: 'fa-cube', ptName: 'Cubo' },
            { name: 'fa-cubes', ptName: 'Cubos' },
            { name: 'fa-cutlery', ptName: 'Talheres' },
            { name: 'fa-dashboard', ptName: 'Painel de controle' },
            { name: 'fa-database', ptName: 'Banco de dados' },
            { name: 'fa-deaf', ptName: 'Surdo' },
            { name: 'fa-deafness', ptName: 'Surdez' },
            { name: 'fa-desktop', ptName: 'Desktop' },
            { name: 'fa-diamond', ptName: 'Diamante' },
            { name: 'fa-download', ptName: 'Download' },
            { name: 'fa-edit', ptName: 'Editar' },
            { name: 'fa-ellipsis-h', ptName: 'Reticências horizontais' },
            { name: 'fa-ellipsis-v', ptName: 'Reticências verticais' },
            { name: 'fa-envelope', ptName: 'Envelope' },
            { name: 'fa-envelope-open', ptName: 'Envelope aberto' },
            { name: 'fa-envelope-square', ptName: 'Envelope quadrado' },
            { name: 'fa-eraser', ptName: 'Borracha' },
            { name: 'fa-exchange', ptName: 'Troca' },
            { name: 'fa-exclamation', ptName: 'Exclamação' },
            { name: 'fa-exclamation-circle', ptName: 'Círculo de exclamação' },
            { name: 'fa-exclamation-triangle', ptName: 'Triângulo de exclamação' },
            { name: 'fa-external-link', ptName: 'Link externo' },
            { name: 'fa-external-link-square', ptName: 'Link externo quadrado' },
            { name: 'fa-eye', ptName: 'Olho' },
            { name: 'fa-eye-slash', ptName: 'Olho com barra' },
            { name: 'fa-eyedropper', ptName: 'Conta-gotas' },
            { name: 'fa-fax', ptName: 'Fax' },
            { name: 'fa-feed', ptName: 'Feed' },
            { name: 'fa-female', ptName: 'Feminino' },
            { name: 'fa-fighter-jet', ptName: 'Caça' },
            { name: 'fa-film', ptName: 'Filme' },
            { name: 'fa-filter', ptName: 'Filtro' },
            { name: 'fa-fire', ptName: 'Fogo' },
            { name: 'fa-fire-extinguisher', ptName: 'Extintor de incêndio' },
            { name: 'fa-flag', ptName: 'Bandeira' },
            { name: 'fa-flag-checkered', ptName: 'Bandeira quadriculada' },
            { name: 'fa-flask', ptName: 'Frasco' },
            { name: 'fa-folder', ptName: 'Pasta' },
            { name: 'fa-folder-open', ptName: 'Pasta aberta' },
            { name: 'fa-gamepad', ptName: 'Controle de jogo' },
            { name: 'fa-gavel', ptName: 'Martelo' },
            { name: 'fa-gear', ptName: 'Engrenagem' },
            { name: 'fa-gears', ptName: 'Engrenagens' },
            { name: 'fa-gift', ptName: 'Presente' },
            { name: 'fa-globe', ptName: 'Globo' },
            { name: 'fa-hard-of-hearing', ptName: 'Dificuldade auditiva' },
            { name: 'fa-hashtag', ptName: 'Hashtag' },
            { name: 'fa-headphones', ptName: 'Fones de ouvido' },
            { name: 'fa-heart', ptName: 'Coração' },
            { name: 'fa-heartbeat', ptName: 'Batimento cardíaco' },
            { name: 'fa-history', ptName: 'Histórico' },
            { name: 'fa-home', ptName: 'Início' },
            { name: 'fa-hotel', ptName: 'Hotel' },
            { name: 'fa-hourglass', ptName: 'Ampulheta' },
            { name: 'fa-hourglass-1', ptName: 'Ampulheta 1' },
            { name: 'fa-hourglass-2', ptName: 'Ampulheta 2' },
            { name: 'fa-hourglass-3', ptName: 'Ampulheta 3' },
            { name: 'fa-hourglass-end', ptName: 'Fim da ampulheta' },
            { name: 'fa-hourglass-half', ptName: 'Ampulheta pela metade' },
            { name: 'fa-hourglass-start', ptName: 'Início da ampulheta' },
            { name: 'fa-i-cursor', ptName: 'Cursor I' },
            { name: 'fa-id-badge', ptName: 'Cracha de identificação' },
            { name: 'fa-id-card', ptName: 'Carteira de identidade' },
            { name: 'fa-image', ptName: 'Imagem' },
            { name: 'fa-inbox', ptName: 'Caixa de entrada' },
            { name: 'fa-industry', ptName: 'Indústria' },
            { name: 'fa-info', ptName: 'Informação' },
            { name: 'fa-info-circle', ptName: 'Círculo de informação' },
            { name: 'fa-institution', ptName: 'Instituição' },
            { name: 'fa-key', ptName: 'Chave' },
            { name: 'fa-language', ptName: 'Idioma' },
            { name: 'fa-laptop', ptName: 'Laptop' },
            { name: 'fa-leaf', ptName: 'Folha' },
            { name: 'fa-legal', ptName: 'Legal' },
            { name: 'fa-level-down', ptName: 'Nivelar para baixo' },
            { name: 'fa-level-up', ptName: 'Nivelar para cima' },
            { name: 'fa-life-ring', ptName: 'Bóia salva-vidas' },
            { name: 'fa-line-chart', ptName: 'Gráfico de linha' },
            { name: 'fa-location-arrow', ptName: 'Seta de localização' },
            { name: 'fa-lock', ptName: 'Cadeado' },
            { name: 'fa-low-vision', ptName: 'Baixa visão' },
            { name: 'fa-magic', ptName: 'Mágica' },
            { name: 'fa-magnet', ptName: 'Ímã' },
            { name: 'fa-mail-forward', ptName: 'Encaminhar e-mail' },
            { name: 'fa-mail-reply', ptName: 'Responder e-mail' },
            { name: 'fa-mail-reply-all', ptName: 'Responder a todos e-mail' },
            { name: 'fa-male', ptName: 'Masculino' },
            { name: 'fa-map', ptName: 'Mapa' },
            { name: 'fa-map-marker', ptName: 'Marcador de mapa' },
            { name: 'fa-map-pin', ptName: 'Alfinete de mapa' },
            { name: 'fa-map-signs', ptName: 'Sinais de mapa' },
            { name: 'fa-microchip', ptName: 'Microchip' },
            { name: 'fa-microphone', ptName: 'Microfone' },
            { name: 'fa-microphone-slash', ptName: 'Microfone com barra' },
            { name: 'fa-minus', ptName: 'Menos' },
            { name: 'fa-minus-circle', ptName: 'Círculo de menos' },
            { name: 'fa-minus-square', ptName: 'Quadrado de menos' },
            { name: 'fa-mobile', ptName: 'Celular' },
            { name: 'fa-dollar', ptName: 'Dólar dinheiro real' },
            { name: 'fa-circle-dollar-to-slot', ptName: 'Dólar dinheiro real' },
            { name: 'fa-piggy-bank', ptName: 'Dólar dinheiro real' },
            { name: 'fa-mortar-board', ptName: 'Capelo formatura graduação' },
            { name: 'fa-motorcycle', ptName: 'Motocicleta' },
            { name: 'fa-mouse-pointer', ptName: 'Ponteiro do mouse' },
            { name: 'fa-music', ptName: 'Música' },
            { name: 'fa-navicon', ptName: 'Navicon' },
            { name: 'fa-object-group', ptName: 'Agrupar objeto' },
            { name: 'fa-object-ungroup', ptName: 'Desagrupar objeto' },
            { name: 'fa-paint-brush', ptName: 'Pincel' },
            { name: 'fa-paper-plane', ptName: 'Avião de papel' },
            { name: 'fa-paw', ptName: 'Pata' },
            { name: 'fa-pencil', ptName: 'Lápis' },
            { name: 'fa-pencil-square', ptName: 'Quadrado de lápis' },
            { name: 'fa-percent', ptName: 'Porcentagem' },
            { name: 'fa-pie-chart', ptName: 'Gráfico de pizza' },
            { name: 'fa-plane', ptName: 'Avião' },
            { name: 'fa-plug', ptName: 'Plugue' },
            { name: 'fa-plus', ptName: 'Mais' },
            { name: 'fa-plus-circle', ptName: 'Círculo de mais' },
            { name: 'fa-plus-square', ptName: 'Quadrado de mais' },
            { name: 'fa-podcast', ptName: 'Podcast' },
            { name: 'fa-power-off', ptName: 'Desligar' },
            { name: 'fa-print', ptName: 'Imprimir' },
            { name: 'fa-puzzle-piece', ptName: 'Peça de quebra-cabeça' },
            { name: 'fa-qrcode', ptName: 'QR Code' },
            { name: 'fa-question', ptName: 'Pergunta' },
            { name: 'fa-question-circle', ptName: 'Círculo de pergunta' },
            { name: 'fa-quote-left', ptName: 'Aspas esquerda' },
            { name: 'fa-quote-right', ptName: 'Aspas direita' },
            { name: 'fa-random', ptName: 'Aleatório' },
            { name: 'fa-recycle', ptName: 'Reciclar' },
            { name: 'fa-refresh', ptName: 'Atualizar' },
            { name: 'fa-registered', ptName: 'Registrado' },
            { name: 'fa-remove', ptName: 'Remover' },
            { name: 'fa-reorder', ptName: 'Reordenar' },
            { name: 'fa-reply', ptName: 'Responder' },
            { name: 'fa-reply-all', ptName: 'Responder a todos' },
            { name: 'fa-retweet', ptName: 'Retweet' },
            { name: 'fa-road', ptName: 'Estrada' },
            { name: 'fa-rocket', ptName: 'Foguete' },
            { name: 'fa-rss', ptName: 'RSS' },
            { name: 'fa-rss-square', ptName: 'RSS quadrado' },
            { name: 'fa-search', ptName: 'Buscar lupa' },
            { name: 'fa-search-minus', ptName: 'Buscar menos lupa' },
            { name: 'fa-search-plus', ptName: 'Buscar mais lupa' },
            { name: 'fa-server', ptName: 'Servidor' },
            { name: 'fa-share', ptName: 'Compartilhar' },
            { name: 'fa-share-alt', ptName: 'Compartilhar alt' },
            { name: 'fa-share-alt-square', ptName: 'Compartilhar alt quadrado' },
            { name: 'fa-share-square', ptName: 'Compartilhar quadrado' },
            { name: 'fa-shield', ptName: 'Escudo' },
            { name: 'fa-ship', ptName: 'Navio' },
            { name: 'fa-shopping-bag', ptName: 'Sacola de compras' },
            { name: 'fa-shopping-basket', ptName: 'Cesta de compras' },
            { name: 'fa-shopping-cart', ptName: 'Carrinho de compras' },
            { name: 'fa-shower', ptName: 'Chuveiro' },
            { name: 'fa-sign-in', ptName: 'Entrar' },
            { name: 'fa-sign-language', ptName: 'Linguagem de sinais' },
            { name: 'fa-sign-out', ptName: 'Sair' },
            { name: 'fa-signal', ptName: 'Sinal' },
            { name: 'fa-signing', ptName: 'Assinatura' },
            { name: 'fa-sitemap', ptName: 'Mapa do site' },
            { name: 'fa-sliders', ptName: 'Deslizantes' },
            { name: 'fa-sort', ptName: 'Ordenar' },
            { name: 'fa-sort-alpha-asc', ptName: 'Ordenar alfa ascendente' },
            { name: 'fa-sort-alpha-desc', ptName: 'Ordenar alfa descendente' },
            { name: 'fa-sort-amount-asc', ptName: 'Ordenar quantidade ascendente' },
            { name: 'fa-sort-amount-desc', ptName: 'Ordenar quantidade descendente' },
            { name: 'fa-sort-desc', ptName: 'Ordenar descendente' },
            { name: 'fa-sort-numeric-asc', ptName: 'Ordenar numérico ascendente' },
            { name: 'fa-sort-up', ptName: 'Ordenar para cima' },
            { name: 'fa-space-shuttle', ptName: 'Ônibus espacial' },
            { name: 'fa-spinner', ptName: 'Spinner' },
            { name: 'fa-spoon', ptName: 'Colher' },
            { name: 'fa-square', ptName: 'Quadrado' },
            { name: 'fa-star', ptName: 'Estrela' },
            { name: 'fa-star-half', ptName: 'Meia estrela' },
            { name: 'fa-sticky-note', ptName: 'Nota adesiva' },
            { name: 'fa-street-view', ptName: 'Vista da rua' },
            { name: 'fa-suitcase', ptName: 'Mala' },
            { name: 'fa-tablet', ptName: 'Tablet' },
            { name: 'fa-tachometer', ptName: 'Tacômetro' },
            { name: 'fa-tag', ptName: 'Etiqueta' },
            { name: 'fa-tags', ptName: 'Etiquetas' },
            { name: 'fa-tasks', ptName: 'Tarefas' },
            { name: 'fa-taxi', ptName: 'Táxi' },
            { name: 'fa-television', ptName: 'Televisão' },
            { name: 'fa-terminal', ptName: 'Terminal' },
            { name: 'fa-thermometer', ptName: 'Termômetro' },
            { name: 'fa-thermometer-empty', ptName: 'Termômetro vazio' },
            { name: 'fa-thermometer-full', ptName: 'Termômetro cheio' },
            { name: 'fa-thumb-tack', ptName: 'Percevejo' },
            { name: 'fa-thumbs-down', ptName: 'Polegar para baixo' },
            { name: 'fa-thumbs-up', ptName: 'Polegar para cima' },
            { name: 'fa-ticket', ptName: 'Bilhete' },
            { name: 'fa-times', ptName: 'Vezes' },
            { name: 'fa-times-circle', ptName: 'Círculo de vezes' },
            { name: 'fa-times-rectangle', ptName: 'Retângulo de vezes' },
            { name: 'fa-tint', ptName: 'Gota' },
            { name: 'fa-toggle-off', ptName: 'Desligar alternância' },
            { name: 'fa-toggle-on', ptName: 'Ligar alternância' },
            { name: 'fa-trash', ptName: 'Lixo' },
            { name: 'fa-tree', ptName: 'Árvore' },
            { name: 'fa-trophy', ptName: 'Troféu' },
            { name: 'fa-truck', ptName: 'Caminhão' },
            { name: 'fa-tty', ptName: 'TTY' },
            { name: 'fa-tv', ptName: 'TV' },
            { name: 'fa-umbrella', ptName: 'Guarda-chuva' },
            { name: 'fa-universal-access', ptName: 'Acesso universal' },
            { name: 'fa-university', ptName: 'Universidade' },
            { name: 'fa-unlock', ptName: 'Destravar' },
            { name: 'fa-unlock-alt', ptName: 'Destravar alt' },
            { name: 'fa-unsorted', ptName: 'Não ordenado' },
            { name: 'fa-upload', ptName: 'Upload' },
            { name: 'fa-user', ptName: 'usuário pessoa  ' },
            { name: 'fa-user-graduate', ptName: 'usuário pessoa   graduação' },
            { name: 'fa-person-chalkboard', ptName: 'usuário pessoa   graduação ensinando profeessor' },
            { name: 'fa-user-circle', ptName: 'Grupo de usuário pessoa  ' },
            { name: 'fa-user-plus', ptName: 'Adicionar usuário pessoa  ' },
            { name: 'fa-user-secret', ptName: 'usuário pessoa   secreto' },
            { name: 'fa-user-times', ptName: 'Excluir usuário pessoa  ' },
            { name: 'fa-users', ptName: 'usuário pessoa  s Grupo' },
            { name: 'fa-vcard', ptName: 'vCard' },
            { name: 'fa-video-camera', ptName: 'Câmera de vídeo' },
            { name: 'fa-volume-control-phone', ptName: 'Telefone com controle de volume' },
            { name: 'fa-volume-down', ptName: 'Volume baixo' },
            { name: 'fa-volume-off', ptName: 'Sem volume' },
            { name: 'fa-volume-up', ptName: 'Volume alto' },
            { name: 'fa-warning', ptName: 'Aviso' },
            { name: 'fa-wheelchair', ptName: 'Cadeira de rodas' },
            { name: 'fa-wheelchair-alt', ptName: 'Cadeira de rodas alt' },
            { name: 'fa-wifi', ptName: 'Wi-Fi' },
            { name: 'fa-window-close', ptName: 'Fechar janela' },
            { name: 'fa-window-maximize', ptName: 'Maximizar janela' },
            { name: 'fa-window-restore', ptName: 'Restaurar janela' },
            { name: 'fa-wrench', ptName: 'Chave inglesa' },
            { name: 'fa-phone', ptName: 'Telefone' },
            { name: 'fa-envelope', ptName: 'Envelope' },
            { name: 'fa-pen-nib', ptName: 'Pena de escrita' },
            { name: 'fa-calendar-days', ptName: 'Calendário de dias' },
            { name: 'fa-paperclip', ptName: 'Clipes de papel' },
            { name: 'fa-file', ptName: 'Arquivo' },
            { name: 'fa-clipboard', ptName: 'Prancheta' },
            { name: 'fa-pen', ptName: 'Caneta' },
            { name: 'fa-tag', ptName: 'Etiqueta' },
            { name: 'fa-book', ptName: 'Livro' },
            { name: 'fa-print', ptName: 'Imprimir' },
            { name: 'fa-pen-to-square', ptName: 'Caneta para quadrado' },
            { name: 'fa-folder', ptName: 'Pasta' },
            { name: 'fa-folder-open', ptName: 'Pasta aberta' },
            { name: 'fa-thumbtack', ptName: 'Alfinete' },
            { name: 'fa-globe', ptName: 'Globo' },
            { name: 'fa-city', ptName: 'Cidade' },
            { name: 'fa-briefcase', ptName: 'Maleta' },
            { name: 'fa-compass', ptName: 'Bússola' },
            { name: 'fa-address-book', ptName: 'Livro de endereços' },
            { name: 'fa-business-time', ptName: 'Tempo de negócios' },
            { name: 'fa-pen-fancy', ptName: 'Caneta elegante' },
            { name: 'fa-mug-saucer', ptName: 'Caneca com pires' },
            { name: 'fa-landmark', ptName: 'Marco' },
            { name: 'fa-chart-simple', ptName: 'Gráfico simples' },
            { name: 'fa-calendar', ptName: 'Calendário' },
            { name: 'fa-pencil', ptName: 'Lápis' },
            { name: 'fa-copy', ptName: 'Copiar' },
            { name: 'fa-table', ptName: 'Mesa' },
            { name: 'fa-building', ptName: 'Prédio' },
            { name: 'fa-network-wired', ptName: 'Rede cabeada' },
            { name: 'fa-tags', ptName: 'Etiquetas' },
            { name: 'fa-registered', ptName: 'Registrado' },
            { name: 'fa-signature', ptName: 'Assinatura' },
            { name: 'fa-sitemap', ptName: 'Mapa do site' },
            { name: 'fa-marker', ptName: 'Marcador' },
            { name: 'fa-wallet', ptName: 'Carteira' },
            { name: 'fa-copyright', ptName: 'Direitos autorais' },
            { name: 'fa-bullseye', ptName: 'Alvo' },
            { name: 'fa-calculator', ptName: 'Calculadora' },
            { name: 'fa-certificate', ptName: 'Certificado' },
            { name: 'fa-percent', ptName: 'Porcentagem' },
            { name: 'fa-eraser', ptName: 'Borracha' },
            { name: 'fa-glasses', ptName: 'Óculos' },
            { name: 'fa-industry', ptName: 'Indústria' },
            { name: 'fa-vault', ptName: 'Cofre' },
            { name: 'fa-trademark', ptName: 'Marca registrada' },
            { name: 'fa-timeline', ptName: 'Linha do tempo' },
            { name: 'fa-thumbtack-slash', ptName: 'Alfinete cortado' },
            { name: 'fa-table-columns', ptName: 'Colunas de tabela' },
            { name: 'fa-stapler', ptName: 'Grampeador' },
            { name: 'fa-square-poll-vertical', ptName: 'Pesquisa quadrada vertical' },
            { name: 'fa-square-poll-horizontal', ptName: 'Pesquisa quadrada horizontal' },
            { name: 'fa-square-phone-flip', ptName: 'Telefone quadrado invertido' },
            { name: 'fa-square-phone', ptName: 'Telefone quadrado' },
            { name: 'fa-square-pen', ptName: 'Caneta quadrada' },
            { name: 'fa-square-envelope', ptName: 'Envelope quadrado' },
            { name: 'fa-socks', ptName: 'Meias' },
            { name: 'fa-scissors', ptName: 'Tesoura' },
            { name: 'fa-scale-unbalanced-flip', ptName: 'Balança desequilibrada invertida' },
            { name: 'fa-scale-unbalanced', ptName: 'Balança desequilibrada' },
            { name: 'fa-scale-balanced', ptName: 'Balança equilibrada' },
            { name: 'fa-phone-slash', ptName: 'Telefone cortado' },
            { name: 'fa-phone-flip', ptName: 'Telefone invertido' },
            { name: 'fa-person-chalkboard', ptName: 'Pessoa no quadro' },
            { name: 'fa-pen-clip', ptName: 'Caneta clipe' },
            { name: 'fa-paste', ptName: 'Colar' },
            { name: 'fa-note-sticky', ptName: 'Nota adesiva' },
            { name: 'fa-magnifying-glass-chart', ptName: 'Lupa em gráfico' },
            { name: 'fa-magnifying-glass-arrow-right', ptName: 'Lupa com seta para a direita' },
            { name: 'fa-list-check', ptName: 'Lista de verificação' },
            { name: 'fa-laptop-file', ptName: 'Arquivo no laptop' },
            { name: 'fa-house-laptop', ptName: 'Casa com laptop' },
            { name: 'fa-highlighter', ptName: 'Marcador' },
            { name: 'fa-folder-tree', ptName: 'Árvore de pastas' },
            { name: 'fa-folder-plus', ptName: 'Adicionar pasta' },
            { name: 'fa-folder-minus', ptName: 'Remover pasta' },
            { name: 'fa-floppy-disk', ptName: 'Disquete' },
            { name: 'fa-file-lines', ptName: 'Arquivo com linhas' },
            { name: 'fa-file-circle-plus', ptName: 'Arquivo com círculo e mais' },
            { name: 'fa-fax', ptName: 'Fax' },
            { name: 'fa-envelope-open', ptName: 'Envelope aberto' },
            { name: 'fa-clipboard-question', ptName: 'Prancheta com interrogação' },
            { name: 'fa-chart-pie', ptName: 'Gráfico de pizza' },
            { name: 'fa-chart-line', ptName: 'Gráfico de linha' },
            { name: 'fa-cake-candles', ptName: 'Bolo com velas' },
            { name: 'fa-boxes-packing', ptName: 'Caixas de embalagem' },
            { name: 'fa-bars-staggered', ptName: 'Barras escalonadas' },
            { name: 'fa-bars-progress', ptName: 'Barras de progresso' },
            { name: 'fa-arrows-to-eye', ptName: 'Setas para o olho' },
            { name: 'fa-arrows-to-dot', ptName: 'Setas para o ponto' },
            { name: 'fa-arrows-spin', ptName: 'Setas girando' },
            { name: 'fa-paste', ptName: 'Colar' },
            { name: 'fa-note-sticky', ptName: 'Nota adesiva' },
            { name: 'fa-floppy-disk', ptName: 'Disquete' },
            { name: 'fa-envelope-open', ptName: 'Envelope aberto' },
            { name: 'fa-house', ptName: 'Casa' },
            { name: 'fa-city', ptName: 'Cidade' },
            { name: 'fa-shop', ptName: 'Loja' },
            { name: 'fa-landmark', ptName: 'Marco' },
            { name: 'fa-building', ptName: 'Prédio' },
            { name: 'fa-building', ptName: 'Prédio' },
            { name: 'fa-store', ptName: 'Loja' },
            { name: 'fa-school', ptName: 'Escola' },
            { name: 'fa-hotel', ptName: 'Hotel' },
            { name: 'fa-place-of-worship', ptName: 'Local de culto' },
            { name: 'fa-hospital', ptName: 'Hospital' },
            { name: 'fa-hospital', ptName: 'Hospital' },
            { name: 'fa-church', ptName: 'Igreja' },
            { name: 'fa-warehouse', ptName: 'Armazém' },
            { name: 'fa-gopuram', ptName: 'Gopuram' },
            { name: 'fa-industry', ptName: 'Indústria' },
            { name: 'fa-vihara', ptName: 'Vihara' },
            { name: 'fa-tree-city', ptName: 'Cidade das árvores' },
            { name: 'fa-tower-observation', ptName: 'Torre de observação' },
            { name: 'fa-torii-gate', ptName: 'Portão Torii' },
            { name: 'fa-toilets-portable', ptName: 'Banheiros portáteis' },
            { name: 'fa-toilet-portable', ptName: 'Banheiro portátil' },
            { name: 'fa-tents', ptName: 'Tendas' },
            { name: 'fa-tent-arrows-down', ptName: 'Tenda com setas para baixo' },
            { name: 'fa-tent-arrow-turn-left', ptName: 'Tenda com seta para a esquerda' },
            { name: 'fa-tent-arrow-left-right', ptName: 'Tenda com seta para a esquerda e direita' },
            { name: 'fa-tent-arrow-down-to-line', ptName: 'Tenda com seta para baixo até a linha' },
            { name: 'fa-tent', ptName: 'Tenda' },
            { name: 'fa-synagogue', ptName: 'Sinagoga' },
            { name: 'fa-shop-lock', ptName: 'Loja bloqueada' },
            { name: 'fa-school-lock', ptName: 'Escola bloqueada' },
            { name: 'fa-school-flag', ptName: 'Escola com bandeira' },
            { name: 'fa-school-circle-xmark', ptName: 'Escola com círculo e X' },
            { name: 'fa-school-circle-exclamation', ptName: 'Escola com círculo e exclamação' },
            { name: 'fa-school-circle-check', ptName: 'Escola com círculo e verificação' },
            { name: 'fa-oil-well', ptName: 'Poço de petróleo' },
            { name: 'fa-mountain-city', ptName: 'Cidade na montanha' },
            { name: 'fa-mosque', ptName: 'Mesquita' },
            { name: 'fa-monument', ptName: 'Monumento' },
            { name: 'fa-landmark-flag', ptName: 'Marco com bandeira' },
            { name: 'fa-landmark-dome', ptName: 'Marco com cúpula' },
            { name: 'fa-kaaba', ptName: 'Kaaba' },
            { name: 'fa-igloo', ptName: 'Iglu' },
            { name: 'fa-house-medical-flag', ptName: 'Casa médica com bandeira' },
            { name: 'fa-house-medical-circle-xmark', ptName: 'Casa médica com círculo e X' },
            { name: 'fa-house-medical-circle-exclamation', ptName: 'Casa médica com círculo e exclamação' },
            { name: 'fa-house-medical-circle-check', ptName: 'Casa médica com círculo e verificação' },
            { name: 'fa-house-medical', ptName: 'Casa médica' },
            { name: 'fa-house-lock', ptName: 'Casa bloqueada' },
            { name: 'fa-house-flag', ptName: 'Casa com bandeira' },
            { name: 'fa-house-fire', ptName: 'Casa em chamas' },
            { name: 'fa-house-crack', ptName: 'Casa rachada' },
            { name: 'fa-house-circle-exclamation', ptName: 'Casa com círculo e exclamação' },
            { name: 'fa-house-circle-check', ptName: 'Casa com círculo e verificação' },
            { name: 'fa-house-chimney-window', ptName: 'Casa com chaminé e janela' },
            { name: 'fa-house-chimney-medical', ptName: 'Casa com chaminé médica' },
            { name: 'fa-house-chimney-crack', ptName: 'Casa com chaminé rachada' },
            { name: 'fa-house-chimney', ptName: 'Casa com chaminé' },
            { name: 'fa-hospital-user', ptName: 'usuário pessoa   do hospital' },
            { name: 'fa-dungeon', ptName: 'Masmorra' },
            { name: 'fa-campground', ptName: 'Camping' },
            { name: 'fa-building-wheat', ptName: 'Prédio de trigo' },
            { name: 'fa-building-user', ptName: 'usuário pessoa   do prédio' },
            { name: 'fa-building-un', ptName: 'Prédio da ONU' },
            { name: 'fa-building-shield', ptName: 'Prédio com escudo' },
            { name: 'fa-building-ngo', ptName: 'Prédio da ONG' },
            { name: 'fa-building-lock', ptName: 'Prédio bloqueado' },
            { name: 'fa-building-flag', ptName: 'Prédio com bandeira' },
            { name: 'fa-building-columns', ptName: 'Prédio com colunas' },
            { name: 'fa-building-circle-xmark', ptName: 'Prédio com círculo e X' },
            { name: 'fa-building-circle-exclamation', ptName: 'Prédio com círculo e exclamação' },
            { name: 'fa-building-circle-check', ptName: 'Prédio com círculo e verificação' },
            { name: 'fa-building-circle-arrow-right', ptName: 'Prédio com círculo e seta para a direita' },
            { name: 'fa-arrow-right-to-city', ptName: 'Seta para a direita para a cidade' },
            { name: 'fa-hand-holding-heart', ptName: 'mão segurando coracao' },
            { name: 'fa-hands-holding-circle', ptName: 'mão segurando' },
            { name: 'fa-handshake-simple', ptName: 'mão aperto mao' },
            { name: 'fa-handshake', ptName: 'mão aperto mao' },
            { name: 'fa-hand-holding-dollar', ptName: 'mão aperto mao dinheiro dolar real' },
            { name: 'fa-award', ptName: 'prêmio premio recompensa' },
            { name: 'fa-microscope', ptName: 'microscopio ciencia ciência' },
            { name: 'fa-masks-theater', ptName: 'teatro arte' },
            { name: 'fa-book-open-reader', ptName: 'livro ler' },
            { name: 'fa-atom', ptName: 'âtomo atomo celula' },
            { name: 'fa-fire', ptName: 'fogo calor' },
            { name: 'fa-sun', ptName: 'sol calor' },
            { name: 'fa-fire-extinguisher', ptName: 'extintor fogo incendio incêncio' },
            { name: 'fa-gas-pump', ptName: 'gas gasolina' },
            { name: 'fa-water', ptName: 'água agua' },
            { name: 'fa-leaf', ptName: 'folha arvore' },
            { name: 'fa-wind', ptName: 'vento' },
        ]);

        onMounted(()=>{
            if(props.value){
                selectedIcon.value = props.value
                console.log(props.value);
            }
        })

        const selectedIcon = ref(null);
        const filterText = ref('');
        const dropdownOpen = ref(false);

        const filteredIcons = computed(() => {
            const search = filterText.value.toLowerCase();
            return icons.value.filter(icon => icon.ptName.toLowerCase().includes(search));
        });

        function selectIcon(icon) {
            selectedIcon.value = icon;
            dropdownOpen.value = false;
        }

        function closeDropdown() {
            setTimeout(() => {
                dropdownOpen.value = false;
            }, 200); // Adiciona um pequeno atraso para permitir a seleção do ícone
        }

        return {
            icons,
            selectedIcon,
            filterText,
            filteredIcons,
            dropdownOpen,
            props,
            selectIcon,
            closeDropdown
        };
    },

    props: {
        value: { default: null, required: false },
        disabled: { default: false, required: false },
    }
};
</script>
<style>
.dropdown {
    position: relative;
    max-width: 200px;
    justify-content: space-between;
}

.dropdown-menu {
    position: absolute;
    top: 100%;
    left: 0;
    display: none;
    max-height: 200px;
    max-width: 100px;
    justify-content: space-between;
    overflow-y: auto;
}

.dropdown-menu.show {
    display: block;
}


.selected-icon-preview {
    display: flex;
    align-items: center;
}

.selected-icon-preview i {
    align-items: center;
}
</style>
